import type { Indicator, MapPoint, Section, Settings, Source } from "./types";

export const DEFAULT_SETTINGS: Settings = {
  site_name: "Código Energía",
  tagline: "Energía, oil & gas y minería en tiempo real",
  description:
    "Medio digital que sigue minuto a minuto la energía, el petróleo, el gas y la minería en la Argentina y la región.",
  accent: "#e5484d",
  categories: [
    { slug: "energia", name: "Energía", color: "#3a3f47", text: "#e5e7eb" },
    { slug: "oil-gas", name: "Oil & Gas", color: "#3b5b9a", text: "#ffffff" },
    { slug: "mineria", name: "Minería", color: "#f5b400", text: "#ffffff" },
    { slug: "electricidad", name: "Electricidad", color: "#0e7490", text: "#ffffff" },
    { slug: "renovables", name: "Renovables", color: "#15803d", text: "#ffffff" },
    { slug: "economia", name: "Economía", color: "#7c3aed", text: "#ffffff" },
  ],
  ticker_enabled: true,
  footer_text: "Código Energía — información sobre energía, oil & gas y minería.",
  social: [],
  scrape_every_min: 30,
  indicators_every_min: 15,
  retention_days: 120,
  ai_rewrite_auto: false,
  brief_prompt:
    "Sos el editor de Código Energía, un medio argentino especializado en energía, oil & gas y minería. " +
    "Escribí el resumen de lo más importante que pasó ayer, en español rioplatense, tono periodístico, claro y sin exagerar. " +
    "Priorizá: producción y exportaciones de Vaca Muerta, precios, decisiones regulatorias, inversiones y minería (litio, cobre, oro).",
  brief_hour: 7,
  brief_audio: true,
  brief_video: false,
  // Servicio WMS público del SIG de la Secretaría de Energía. Desde el back office
  // se pueden explorar todas las capas del servidor y sumar las que hagan falta.
  map_layers: [
    { id: "se-gasoductos-proy", label: "Gasoductos proyectados (SE)", url: "https://sig.energia.gob.ar/wmsenergia", layers: "hidtransp_gasoductos_proyectados", enabled: true, visible: true, opacity: 0.9 },
    { id: "se-oleoductos-proy", label: "Oleoductos proyectados (SE)", url: "https://sig.energia.gob.ar/wmsenergia", layers: "hidrocarburos_transporte_oleoductos_proyectados", enabled: true, visible: true, opacity: 0.9 },
    { id: "se-compresoras", label: "Plantas compresoras (ENARGAS)", url: "https://sig.energia.gob.ar/wmsenergia", layers: "enargas_plantas_compresoras", enabled: true, visible: false, opacity: 1 },
  ],
};

const gn = (q: string) => q;

export const DEFAULT_SOURCES: Omit<Source, "last_run_at" | "last_status" | "last_count">[] = [
  {
    id: "gn-vaca-muerta",
    name: "Google News · Vaca Muerta",
    type: "google_news",
    url: gn('"Vaca Muerta" OR "shale" Neuquén'),
    category: "oil-gas",
    enabled: true,
    auto_publish: true,
    include_keywords: [],
    exclude_keywords: ["fútbol", "horóscopo"],
    max_items: 20,
    fetch_meta: false,
  },
  {
    id: "gn-petroleo",
    name: "Google News · Petróleo y gas",
    type: "google_news",
    url: gn("YPF OR Vista OR \"Pampa Energía\" OR Tecpetrol OR Chevron petróleo Argentina"),
    category: "oil-gas",
    enabled: true,
    auto_publish: true,
    include_keywords: [],
    exclude_keywords: [],
    max_items: 20,
    fetch_meta: false,
  },
  {
    id: "gn-mineria",
    name: "Google News · Minería",
    type: "google_news",
    url: gn("minería Argentina OR litio OR cobre San Juan OR Catamarca minera"),
    category: "mineria",
    enabled: true,
    auto_publish: true,
    include_keywords: [],
    exclude_keywords: ["bitcoin", "cripto"],
    max_items: 20,
    fetch_meta: false,
  },
  {
    id: "gn-energia",
    name: "Google News · Energía",
    type: "google_news",
    url: gn("CAMMESA OR ENARSA OR \"Secretaría de Energía\" OR tarifas energía Argentina"),
    category: "energia",
    enabled: true,
    auto_publish: true,
    include_keywords: [],
    exclude_keywords: [],
    max_items: 20,
    fetch_meta: false,
  },
  {
    id: "gn-renovables",
    name: "Google News · Renovables",
    type: "google_news",
    url: gn("parque solar OR parque eólico OR renovables Argentina"),
    category: "renovables",
    enabled: true,
    auto_publish: true,
    include_keywords: [],
    exclude_keywords: [],
    max_items: 15,
    fetch_meta: false,
  },
  {
    id: "econojournal",
    name: "EconoJournal",
    type: "rss",
    url: "https://econojournal.com.ar/feed/",
    category: "energia",
    enabled: true,
    auto_publish: true,
    include_keywords: [],
    exclude_keywords: [],
    max_items: 20,
    fetch_meta: true,
  },
  {
    id: "energia-estrategica",
    name: "Energía Estratégica",
    type: "rss",
    url: "https://www.energiaestrategica.com/feed/",
    category: "renovables",
    enabled: true,
    auto_publish: true,
    include_keywords: ["Argentina", "argentin", "Chile", "Uruguay"],
    exclude_keywords: [],
    max_items: 15,
    fetch_meta: true,
  },
  {
    id: "surtidores",
    name: "Surtidores",
    type: "rss",
    url: "https://surtidores.com.ar/feed/",
    category: "oil-gas",
    enabled: true,
    auto_publish: true,
    include_keywords: [],
    exclude_keywords: [],
    max_items: 15,
    fetch_meta: true,
  },
  {
    id: "panorama-minero",
    name: "Panorama Minero",
    type: "rss",
    url: "https://www.panorama-minero.com/feed/",
    category: "mineria",
    enabled: true,
    auto_publish: true,
    include_keywords: [],
    exclude_keywords: [],
    max_items: 15,
    fetch_meta: true,
  },
];

let order = 0;
const ind = (i: Omit<Indicator, "order" | "enabled" | "show_in_panel"> & Partial<Indicator>): Indicator => ({
  enabled: true,
  show_in_panel: true,
  order: order++,
  ...i,
});

export const DEFAULT_INDICATORS: Indicator[] = [
  ind({ id: "wti", label: "WTI", group: "Commodities", provider: "yahoo", param: "CL=F", unit: "USD/bbl", decimals: 2, show_in_ticker: true }),
  ind({ id: "brent", label: "Brent", group: "Commodities", provider: "yahoo", param: "BZ=F", unit: "USD/bbl", decimals: 2, show_in_ticker: true }),
  ind({ id: "gas-ng", label: "Gas (NG)", group: "Commodities", provider: "yahoo", param: "NG=F", unit: "USD/MMBtu", decimals: 3, show_in_ticker: true }),
  ind({ id: "oro", label: "Oro", group: "Commodities", provider: "yahoo", param: "GC=F", unit: "USD/oz", decimals: 0, show_in_ticker: true }),
  ind({ id: "plata", label: "Plata", group: "Commodities", provider: "yahoo", param: "SI=F", unit: "USD/oz", decimals: 2, show_in_ticker: true }),
  ind({ id: "cobre", label: "Cobre", group: "Commodities", provider: "yahoo", param: "HG=F", unit: "USD/lb", decimals: 2, show_in_ticker: true }),
  ind({ id: "litio", label: "Litio (LIT ETF)", group: "Commodities", provider: "yahoo", param: "LIT", unit: "USD", decimals: 2, show_in_ticker: true }),
  ind({ id: "dolar-oficial", label: "Dólar oficial", group: "Dólar", provider: "dolarapi", param: "oficial", unit: "ARS", decimals: 0, show_in_ticker: true }),
  ind({ id: "dolar-blue", label: "Dólar blue", group: "Dólar", provider: "dolarapi", param: "blue", unit: "ARS", decimals: 0, show_in_ticker: true }),
  ind({ id: "dolar-mep", label: "Dólar MEP", group: "Dólar", provider: "dolarapi", param: "bolsa", unit: "ARS", decimals: 0, show_in_ticker: false }),
  ind({ id: "dolar-ccl", label: "Dólar CCL", group: "Dólar", provider: "dolarapi", param: "contadoconliqui", unit: "ARS", decimals: 0, show_in_ticker: false }),
  ind({ id: "merval", label: "Merval", group: "Bolsa", provider: "yahoo", param: "^MERV", unit: "pts", decimals: 0, show_in_ticker: true }),
  ind({ id: "ypf", label: "YPF", group: "Bolsa", provider: "yahoo", param: "YPF", unit: "USD", decimals: 2, show_in_ticker: true }),
  ind({ id: "vist", label: "Vista", group: "Bolsa", provider: "yahoo", param: "VIST", unit: "USD", decimals: 2, show_in_ticker: true }),
  ind({ id: "pam", label: "Pampa", group: "Bolsa", provider: "yahoo", param: "PAM", unit: "USD", decimals: 2, show_in_ticker: true }),
  ind({ id: "tgs", label: "TGS", group: "Bolsa", provider: "yahoo", param: "TGS", unit: "USD", decimals: 2, show_in_ticker: false }),
  // Contadores en vivo: valor base en counter_start + ritmo diario. Ajustar desde el back office
  // con los datos oficiales (Secretaría de Energía / SIPG) cuando se publiquen.
  ind({
    id: "barriles-vm", label: "Barriles extraídos · Vaca Muerta", group: "Contadores", provider: "counter", param: "",
    unit: "bbl", decimals: 0, show_in_ticker: false, counter_start: "2025-12-31T00:00:00-03:00", counter_base: 0,
    counter_rate_per_day: 876000, note: "Ritmo estimado. Actualizar con datos oficiales.",
  }),
  ind({
    id: "gas-inyectado", label: "Gas inyectado", group: "Contadores", provider: "counter", param: "",
    unit: "m³", decimals: 0, show_in_ticker: false, counter_start: "2025-12-31T00:00:00-03:00", counter_base: 0,
    counter_rate_per_day: 241400000, note: "Ritmo estimado. Actualizar con datos oficiales.",
  }),
  ind({
    id: "litio-extraido", label: "Litio extraído", group: "Contadores", provider: "counter", param: "",
    unit: "gramos", decimals: 0, show_in_ticker: false, counter_start: "2025-12-31T00:00:00-03:00", counter_base: 0,
    counter_rate_per_day: 109300000, note: "Ritmo estimado. Actualizar con datos oficiales.",
  }),
];

let sOrder = 0;
const sec = (s: Omit<Section, "order" | "enabled" | "category"> & Partial<Section>): Section => ({
  enabled: true,
  category: "",
  order: sOrder++,
  ...s,
});

export const DEFAULT_SECTIONS: Section[] = [
  sec({ id: "newsroom", type: "newsroom", title: "Redacción · en vivo", limit: 8 }),
  sec({ id: "hero", type: "hero", title: "Principal", limit: 1 }),
  sec({ id: "counters", type: "counters", title: "Contadores", limit: 3 }),
  sec({ id: "ultimas", type: "list", title: "Últimas noticias", limit: 6, offset: 1 }),
  sec({ id: "brief", type: "daily_brief", title: "El resumen de ayer", limit: 1 }),
  sec({ id: "mas-leidas", type: "most_read", title: "Más leídas", limit: 6, columns: 2 }),
  sec({ id: "oil-gas", type: "grid", title: "Oil & Gas", category: "oil-gas", limit: 4, columns: 2 }),
  sec({ id: "mineria", type: "grid", title: "Minería", category: "mineria", limit: 4, columns: 2 }),
  sec({ id: "mapa", type: "map", title: "El mapa de la energía", limit: 0 }),
  sec({ id: "energia", type: "list", title: "Energía", category: "energia", limit: 5 }),
  sec({ id: "renovables", type: "grid", title: "Renovables", category: "renovables", limit: 4, columns: 2 }),
  sec({ id: "mercados", type: "indicators", title: "Mercados", limit: 0 }),
];

const pt = (p: Omit<MapPoint, "enabled">): MapPoint => ({ enabled: true, ...p });
const APROX = "Ubicación aproximada.";

export const DEFAULT_MAP_POINTS: MapPoint[] = [
  pt({ id: "loma-campana", name: "Loma Campana", type: "yacimiento", lat: -38.25, lng: -68.93, province: "Neuquén", operator: "YPF / Chevron", description: `Principal desarrollo de shale oil de Vaca Muerta. ${APROX}` }),
  pt({ id: "la-amarga-chica", name: "La Amarga Chica", type: "yacimiento", lat: -38.17, lng: -68.72, province: "Neuquén", operator: "YPF / Petronas", description: APROX }),
  pt({ id: "bajada-del-palo", name: "Bajada del Palo", type: "yacimiento", lat: -38.33, lng: -68.55, province: "Neuquén", operator: "Vista", description: APROX }),
  pt({ id: "fortin-de-piedra", name: "Fortín de Piedra", type: "yacimiento", lat: -38.45, lng: -68.65, province: "Neuquén", operator: "Tecpetrol", description: `Shale gas. ${APROX}` }),
  pt({ id: "el-trapial", name: "El Trapial", type: "yacimiento", lat: -37.38, lng: -69.12, province: "Neuquén", operator: "Chevron", description: APROX }),
  pt({ id: "tratayen", name: "Tratayén — cabecera GPM", type: "gasoducto", lat: -38.42, lng: -68.58, province: "Neuquén", operator: "ENARSA", description: `Inicio del Gasoducto Perito Moreno. ${APROX}` }),
  pt({ id: "ref-la-plata", name: "Refinería La Plata", type: "refineria", lat: -34.88, lng: -57.9, province: "Buenos Aires", operator: "YPF", description: APROX }),
  pt({ id: "ref-lujan", name: "Refinería Luján de Cuyo", type: "refineria", lat: -33.02, lng: -68.87, province: "Mendoza", operator: "YPF", description: APROX }),
  pt({ id: "ref-campana", name: "Refinería Campana", type: "refineria", lat: -34.18, lng: -58.96, province: "Buenos Aires", operator: "Pan American Energy (Axion)", description: APROX }),
  pt({ id: "ref-dock-sud", name: "Refinería Dock Sud", type: "refineria", lat: -34.65, lng: -58.34, province: "Buenos Aires", operator: "Raízen", description: APROX }),
  pt({ id: "ref-plaza-huincul", name: "Refinería Plaza Huincul", type: "refineria", lat: -38.93, lng: -69.2, province: "Neuquén", operator: "YPF", description: APROX }),
  pt({ id: "puerto-rosales", name: "Puerto Rosales", type: "puerto", lat: -38.92, lng: -62.07, province: "Buenos Aires", operator: "Oiltanking Ebytem", description: `Terminal de exportación de crudo. ${APROX}` }),
  pt({ id: "punta-colorada", name: "Punta Colorada (VMOS)", type: "puerto", lat: -41.72, lng: -65.03, province: "Río Negro", operator: "VMOS", description: `Terminal del oleoducto Vaca Muerta Oil Sur. ${APROX}` }),
  pt({ id: "gnl-escobar", name: "Terminal GNL Escobar", type: "puerto", lat: -34.28, lng: -58.78, province: "Buenos Aires", operator: "ENARSA", description: APROX }),
  pt({ id: "atucha", name: "Atucha I y II", type: "nuclear", lat: -33.97, lng: -59.21, province: "Buenos Aires", operator: "Nucleoeléctrica", description: APROX }),
  pt({ id: "embalse", name: "Central Nuclear Embalse", type: "nuclear", lat: -32.23, lng: -64.44, province: "Córdoba", operator: "Nucleoeléctrica", description: APROX }),
  pt({ id: "yacyreta", name: "Yacyretá", type: "hidro", lat: -27.48, lng: -56.73, province: "Corrientes", operator: "EBY", description: APROX }),
  pt({ id: "salto-grande", name: "Salto Grande", type: "hidro", lat: -31.27, lng: -57.94, province: "Entre Ríos", operator: "CTM Salto Grande", description: APROX }),
  pt({ id: "el-chocon", name: "El Chocón", type: "hidro", lat: -39.27, lng: -68.76, province: "Neuquén", description: APROX }),
  pt({ id: "ct-san-martin", name: "Central Térmica San Martín", type: "termica", lat: -32.67, lng: -60.78, province: "Santa Fe", description: APROX }),
  pt({ id: "ct-belgrano", name: "Central Térmica Belgrano", type: "termica", lat: -34.2, lng: -58.99, province: "Buenos Aires", description: APROX }),
  pt({ id: "cauchari-solar", name: "Parque Solar Cauchari", type: "solar", lat: -23.25, lng: -66.65, province: "Jujuy", operator: "JEMSE", description: APROX }),
  pt({ id: "pe-rawson", name: "Parque Eólico Rawson", type: "eolico", lat: -43.3, lng: -65.1, province: "Chubut", operator: "Genneia", description: APROX }),
  pt({ id: "pe-madryn", name: "Parque Eólico Madryn", type: "eolico", lat: -42.8, lng: -65.15, province: "Chubut", operator: "Genneia", description: APROX }),
  pt({ id: "veladero", name: "Mina Veladero", type: "mina", lat: -29.37, lng: -69.95, province: "San Juan", operator: "Barrick / Shandong Gold", description: `Oro. ${APROX}` }),
  pt({ id: "vicuna", name: "Vicuña (Josemaría / Filo del Sol)", type: "mina", lat: -28.46, lng: -69.58, province: "San Juan", operator: "BHP / Lundin", description: `Cobre, oro y plata. ${APROX}` }),
  pt({ id: "los-azules", name: "Los Azules", type: "mina", lat: -31.07, lng: -70.23, province: "San Juan", operator: "McEwen Copper", description: `Cobre. ${APROX}` }),
  pt({ id: "cerro-negro", name: "Cerro Negro", type: "mina", lat: -46.83, lng: -70.28, province: "Santa Cruz", operator: "Newmont", description: `Oro. ${APROX}` }),
  pt({ id: "olaroz", name: "Salar de Olaroz", type: "litio", lat: -23.5, lng: -66.7, province: "Jujuy", operator: "Rio Tinto", description: APROX }),
  pt({ id: "cauchari-olaroz", name: "Cauchari-Olaroz", type: "litio", lat: -23.62, lng: -66.73, province: "Jujuy", operator: "Minera Exar", description: APROX }),
  pt({ id: "hombre-muerto", name: "Salar del Hombre Muerto", type: "litio", lat: -25.4, lng: -67.0, province: "Catamarca", operator: "Rio Tinto / POSCO", description: APROX }),
];
